//! Contract test for WAVE-31.04 verifying cross-process / cross-namespace key resolution
//! between CLI (`xavier keys`) and Clavis HTTP handlers (`/v1/clavis/keys/*`).

use axum::extract::Path;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use xavier::adapters::inbound::http::handlers::clavis::get_clavis_key_handler;
use xavier::secrets::keygen::{self, KeyScope};
use xavier::secrets::vault::HardwareVault;

fn setup_isolated_env() -> tempfile::TempDir {
    let tmp = tempfile::tempdir().expect("tempdir");
    std::env::set_var("HOME", tmp.path());
    std::env::set_var("XAVIER_DATA_DIR", tmp.path());
    tmp
}

#[tokio::test]
#[serial_test::serial]
async fn test_cli_keys_generate_and_http_read_contract() {
    let _tmp = setup_isolated_env();

    // 1. Simulate key generated by CLI (`xavier keys generate --name e2e_cli_probe`)
    // CLI uses service "xavier-clavis"
    let cli_vault = HardwareVault::new("xavier-clavis");
    let _ = cli_vault.delete_secret("api_key_e2e_cli_probe");
    let _ = cli_vault.delete_secret("api_key_e2e_cli_probe_meta");
    let _ = cli_vault.delete_secret("e2e_cli_probe");

    let key = keygen::generate_key(
        &cli_vault,
        "e2e_cli_probe",
        KeyScope::Live,
        3600,
        chrono::Utc::now(),
    )
    .expect("generate CLI key");

    assert!(key.value.starts_with("xavier_live_"));

    // 2. Direct read via KeyVault / HardwareVault export
    let exported = keygen::export_key(&cli_vault, "e2e_cli_probe").expect("export key");
    assert_eq!(exported, key.value);

    // 3. Test HTTP handler reading prefixed name
    let response = get_clavis_key_handler(Path("api_key_e2e_cli_probe".to_string()))
        .await
        .into_response();
    assert_eq!(response.status(), StatusCode::OK);
    let body = axum::body::to_bytes(response.into_body(), 64 * 1024)
        .await
        .expect("bytes");
    let json: serde_json::Value = serde_json::from_slice(&body).expect("json");
    assert_eq!(json["value"], key.value);

    // 4. Plain (un-prefixed) names are outside the Clavis namespace: rejected.
    let response_plain = get_clavis_key_handler(Path("e2e_cli_probe".to_string()))
        .await
        .into_response();
    assert_eq!(response_plain.status(), StatusCode::BAD_REQUEST);

    // Cleanup
    let _ = cli_vault.delete_secret("api_key_e2e_cli_probe");
    let _ = cli_vault.delete_secret("api_key_e2e_cli_probe_meta");
    let _ = cli_vault.delete_secret("e2e_cli_probe");
}

#[tokio::test]
#[serial_test::serial]
async fn test_legacy_global_vault_entries_are_not_served_or_migrated() {
    let _tmp = setup_isolated_env();

    let legacy_vault = HardwareVault::new("xavier");
    let clavis_vault = HardwareVault::new("xavier-clavis");

    let _ = legacy_vault.delete_secret("api_key_legacy_probe");
    let _ = legacy_vault.delete_secret("api_key_legacy_probe_meta");
    let _ = clavis_vault.delete_secret("api_key_legacy_probe");
    let _ = clavis_vault.delete_secret("api_key_legacy_probe_meta");
    let _ = clavis_vault.delete_secret("legacy_probe");

    // Legacy Clavis API key stored under "xavier" service namespace with "api_key_" prefix
    legacy_vault
        .store_secret(
            "api_key_legacy_probe",
            "xavier_live_legacy_secret_value_123",
        )
        .expect("store legacy secret");

    let read_back = legacy_vault
        .get_secret("api_key_legacy_probe")
        .expect("read legacy");
    assert_eq!(read_back, "xavier_live_legacy_secret_value_123");

    // The isolated Clavis vault must not read (or migrate) the global vault.
    let response = get_clavis_key_handler(Path("api_key_legacy_probe".to_string()))
        .await
        .into_response();
    assert_eq!(response.status(), StatusCode::NOT_FOUND);
    assert!(clavis_vault.get_secret("api_key_legacy_probe").is_err());

    // Cleanup
    let _ = legacy_vault.delete_secret("api_key_legacy_probe");
    let _ = clavis_vault.delete_secret("api_key_legacy_probe");
    let _ = clavis_vault.delete_secret("legacy_probe");
}

#[tokio::test]
#[serial_test::serial]
async fn test_security_gate_general_secrets_unreachable_via_clavis_handler() {
    let _tmp = setup_isolated_env();

    // Seed a general secret under "xavier" service namespace (e.g. XAVIER_OPENROUTER_API_KEY)
    let general_vault = HardwareVault::new("xavier");
    let clavis_vault = HardwareVault::new("xavier-clavis");

    let _ = general_vault.delete_secret("XAVIER_OPENROUTER_API_KEY");
    let _ = clavis_vault.delete_secret("XAVIER_OPENROUTER_API_KEY");
    let _ = clavis_vault.delete_secret("api_key_XAVIER_OPENROUTER_API_KEY");

    general_vault
        .store_secret(
            "XAVIER_OPENROUTER_API_KEY",
            "sk-or-v1-secret-token-123456789",
        )
        .expect("store general secret");

    // Attempt to query general secret via Clavis HTTP handler using raw key name
    let response = get_clavis_key_handler(Path("XAVIER_OPENROUTER_API_KEY".to_string()))
        .await
        .into_response();

    // MUST be rejected (400) before the vault is consulted
    assert_eq!(
        response.status(),
        StatusCode::BAD_REQUEST,
        "General secret in 'xavier' namespace must NOT be accessible via /v1/clavis/keys/*"
    );

    // Attempt to query with api_key_ prefix (nonexistent in legacy vault)
    let response_prefixed =
        get_clavis_key_handler(Path("api_key_XAVIER_OPENROUTER_API_KEY".to_string()))
            .await
            .into_response();

    assert_eq!(
        response_prefixed.status(),
        StatusCode::NOT_FOUND,
        "Prefixed probe for general secret must also return 404 NOT FOUND"
    );

    // Verify secret was NOT migrated to xavier-clavis
    assert!(clavis_vault
        .get_secret("XAVIER_OPENROUTER_API_KEY")
        .is_err());
    assert!(clavis_vault
        .get_secret("api_key_XAVIER_OPENROUTER_API_KEY")
        .is_err());

    // Cleanup
    let _ = general_vault.delete_secret("XAVIER_OPENROUTER_API_KEY");
}

#[tokio::test]
#[serial_test::serial]
async fn test_rejection_of_non_api_key_legacy_secret() {
    let _tmp = setup_isolated_env();

    let legacy_vault = HardwareVault::new("xavier");
    let clavis_vault = HardwareVault::new("xavier-clavis");

    let _ = legacy_vault.delete_secret("node_private_seed");
    let _ = clavis_vault.delete_secret("node_private_seed");

    legacy_vault
        .store_secret("node_private_seed", "0123456789abcdef0123456789abcdef")
        .expect("store node seed");

    let response = get_clavis_key_handler(Path("node_private_seed".to_string()))
        .await
        .into_response();

    assert_eq!(
        response.status(),
        StatusCode::BAD_REQUEST,
        "Non-api_key name must be rejected outright"
    );

    assert!(clavis_vault.get_secret("node_private_seed").is_err());

    // Cleanup
    let _ = legacy_vault.delete_secret("node_private_seed");
}
