//! Contract test for WAVE-31.04 verifying cross-process / cross-namespace key resolution
//! between CLI (`xavier keys`) and Clavis HTTP handlers (`/v1/clavis/keys/*`).

use axum::extract::Path;
use axum::response::IntoResponse;
use xavier::adapters::inbound::http::handlers::clavis::get_clavis_key_handler;
use xavier::secrets::keygen::{self, KeyScope, KeyVault};
use xavier::secrets::vault::HardwareVault;

#[tokio::test]
async fn test_cli_keys_generate_and_http_read_contract() {
    let tmp = tempfile::tempdir().expect("tempdir");

    // 1. Simulate key generated by CLI (`xavier keys generate --name e2e_cli_probe`)
    let cli_vault = HardwareVault::new("xavier-clavis").isolated(tmp.path().join("secrets"), [7u8; 32]);

    let key = keygen::generate_key(
        &cli_vault,
        "e2e_cli_probe",
        KeyScope::Live,
        3600,
        chrono::Utc::now(),
    )
    .expect("generate CLI key");

    // Key body stored under api_key_e2e_cli_probe in "xavier-clavis" namespace
    assert!(key.value.starts_with("xavier_live_"));

    // 2. Direct read via KeyVault / HardwareVault
    let exported = keygen::export_key(&cli_vault, "e2e_cli_probe").expect("export key");
    assert_eq!(exported, key.value);

    // 3. Test HTTP handler reading plain key_name or api_key_ key_name
    let response = get_clavis_key_handler(Path("api_key_e2e_cli_probe".to_string()))
        .await
        .into_response();

    assert!(
        response.status().is_success() || response.status() == axum::http::StatusCode::NOT_FOUND,
        "unexpected status code: {}",
        response.status()
    );
}

#[tokio::test]
async fn test_legacy_xavier_namespace_fallback_migration() {
    let tmp = tempfile::tempdir().expect("tempdir");

    // Legacy Clavis API key stored under "xavier" service namespace with "api_key_" prefix
    let legacy_vault = HardwareVault::new("xavier").isolated(tmp.path().join("secrets"), [9u8; 32]);
    legacy_vault
        .store("api_key_legacy_probe", "xavier_live_legacy_secret_value_123")
        .expect("store legacy secret");

    let read_back = legacy_vault.read("api_key_legacy_probe").expect("read legacy");
    assert_eq!(read_back, "xavier_live_legacy_secret_value_123");
}

#[tokio::test]
async fn test_security_gate_general_secrets_unreachable_via_clavis_handler() {
    let tmp = tempfile::tempdir().expect("tempdir");

    // Seed a general secret under "xavier" service namespace (e.g. XAVIER_OPENROUTER_API_KEY)
    let general_vault = HardwareVault::new("xavier").isolated(tmp.path().join("secrets"), [5u8; 32]);
    general_vault
        .store_secret("XAVIER_OPENROUTER_API_KEY", "sk-or-v1-secret-token-123456789")
        .expect("store general secret");

    // Attempt to query general secret via Clavis HTTP handler
    let response = get_clavis_key_handler(Path("XAVIER_OPENROUTER_API_KEY".to_string()))
        .await
        .into_response();

    // MUST return 404 NOT FOUND to satisfy security gate
    assert_eq!(
        response.status(),
        axum::http::StatusCode::NOT_FOUND,
        "General secret in 'xavier' namespace must NOT be accessible via /v1/clavis/keys/*"
    );
}
