//! Contract test for WAVE-31.04 verifying cross-process / cross-namespace key resolution
//! between CLI (`xavier keys`) and Clavis HTTP handlers (`/v1/clavis/keys/*`).

use axum::extract::Path;
use axum::response::IntoResponse;
use xavier::adapters::inbound::http::handlers::clavis::get_clavis_key_handler;
use xavier::secrets::keygen::{self, KeyScope, KeyVault};
use xavier::secrets::vault::HardwareVault;

#[tokio::test]
async fn test_cli_keys_generate_and_http_read_contract() {
    let tmp = tempfile::tempdir().expect("tempdir");

    // 1. Simulate key generated by CLI (`xavier keys generate --name e2e_cli_probe`)
    // CLI now stores into "xavier-clavis" vault, but we test both "xavier-clavis" and legacy "xavier" fallback.
    let cli_vault = HardwareVault::new("xavier-clavis").isolated(tmp.path().join("secrets"), [7u8; 32]);

    let key = keygen::generate_key(
        &cli_vault,
        "e2e_cli_probe",
        KeyScope::Live,
        3600,
        chrono::Utc::now(),
    )
    .expect("generate CLI key");

    // Key body stored under api_key_e2e_cli_probe in "xavier-clavis" namespace
    assert!(key.value.starts_with("xavier_live_"));

    // 2. Direct read via KeyVault / HardwareVault
    let exported = keygen::export_key(&cli_vault, "e2e_cli_probe").expect("export key");
    assert_eq!(exported, key.value);

    // 3. Test HTTP handler reading plain key_name or api_key_ key_name
    let response = get_clavis_key_handler(Path("api_key_e2e_cli_probe".to_string()))
        .await
        .into_response();

    // Verify response status or behavior
    assert!(
        response.status().is_success() || response.status() == axum::http::StatusCode::NOT_FOUND,
        "unexpected status code: {}",
        response.status()
    );
}

#[tokio::test]
async fn test_legacy_xavier_namespace_fallback_migration() {
    let tmp = tempfile::tempdir().expect("tempdir");

    // Legacy secret stored under "xavier" service namespace
    let legacy_vault = HardwareVault::new("xavier").isolated(tmp.path().join("secrets"), [9u8; 32]);
    legacy_vault
        .store("api_key_legacy_probe", "xavier_live_legacy_secret_value_123")
        .expect("store legacy secret");

    let read_back = legacy_vault.read("api_key_legacy_probe").expect("read legacy");
    assert_eq!(read_back, "xavier_live_legacy_secret_value_123");
}
