#!/usr/bin/env python3
"""
colab_cli_runner.py — Google Colab CLI Automation Wrapper for Xavier SLMs.

Integrates Xavier's data-commons with Google Colab fine-tuning workflows via:
1. Direct Google Colab / GDrive automation (using `colab-cli` or Google Drive API).
2. Jupyter Notebook generation with self-contained LoRA + GGUF export cells.
3. Pre-execution anonymization audit validation.

Usage:
  python3 colab_cli_runner.py --dataset-dir ./datalake --output-notebook ./xavier_colab_train.ipynb
"""

import os
import sys
import json
import argparse
import subprocess
from pathlib import Path

def parse_args():
    parser = argparse.ArgumentParser(description="Xavier Google Colab CLI & Notebook Pipeline")
    parser.add_argument("--dataset-dir", type=str, default="./datalake", help="Path to exported Xavier dataset directory")
    parser.add_argument("--output-notebook", type=str, default="./xavier_slm_colab_train.ipynb", help="Output path for runnable Colab notebook")
    parser.add_argument("--base-model", type=str, default="Qwen/Qwen2.5-Coder-0.5B-Instruct", help="Base SLM model (0.5B to 3B)")
    parser.add_argument("--target-expert", type=str, default="ast_blast_expert", help="Name identifier of the micro-expert")
    parser.add_argument("--check-audit", action="store_true", default=True, help="Verify anonymization_audit.json before generating")
    return parser.parse_args()

def verify_anonymization_audit(dataset_dir: Path) -> bool:
    audit_file = dataset_dir / "anonymization_audit.json"
    manifest_file = dataset_dir / "bundle_manifest.json"
    
    if not manifest_file.exists():
        print(f"[WARN] No bundle_manifest.json found in {dataset_dir}. Ensure 'xavier data-commons export-training-bundle' ran.")
        return False
        
    if audit_file.exists():
        with open(audit_file, "r") as f:
            try:
                audit = json.load(f)
                excluded_no_consent = audit.get("excluded_records_no_consent", 0)
                excluded_revoked = audit.get("excluded_records_revoked", 0)
                included = audit.get("included_records", 0)
                print(f"[AUDIT] Verified: {included} records included. {excluded_no_consent} excluded (no-consent), {excluded_revoked} excluded (revoked).")
            except Exception as e:
                print(f"[WARN] Error reading audit file: {e}")
    else:
        print(f"[INFO] Audit summary embedded in manifest.")
    return True

def generate_colab_notebook(output_path: Path, base_model: str, expert_name: str):
    """
    Generates an optimized, ready-to-run Jupyter Notebook for Google Colab Free (T4 GPU).
    """
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# 🧠 Xavier SLM Micro-Expert Fine-Tuning: {expert_name}\n",
                    f"**Base Model:** `{base_model}` | **Target:** Compact GGUF (Q4_K_M)\n",
                    "\n",
                    "This notebook was generated by the Xavier Cognitive Engine CLI.\n",
                    "It consumes an anonymized training bundle (`train.jsonl` / `eval.jsonl`) sanitized under **Privacy Level P3**."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 1. Install optimized fine-tuning dependencies\n",
                    "!pip install -q --upgrade pip\n",
                    "!pip install -q torch transformers datasets peft accelerate bitsandbytes trl\n",
                    "# Install llama.cpp build tools for GGUF conversion\n",
                    "!git clone --depth 1 https://github.com/ggerganov/llama.cpp.git /tmp/llama_cpp\n",
                    "!pip install -q -r /tmp/llama_cpp/requirements.txt"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 2. Mount Google Drive or upload local train.jsonl\n",
                    "from google.colab import files\n",
                    "import os\n",
                    "\n",
                    "if not os.path.exists('train.jsonl'):\n",
                    "    print('Please upload train.jsonl exported from Xavier:')\n",
                    "    uploaded = files.upload()\n",
                    "else:\n",
                    "    print('Found existing train.jsonl in workspace.')"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 3. Execute Xavier LoRA Fine-Tuning\n",
                    "import torch\n",
                    "from datasets import load_dataset\n",
                    "from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, BitsAndBytesConfig\n",
                    "from peft import LoraConfig, get_peft_model, TaskType\n",
                    "from trl import SFTTrainer\n",
                    "\n",
                    f"MODEL_ID = '{base_model}'\n",
                    "bnb_config = BitsAndBytesConfig(\n",
                    "    load_in_4bit=True,\n",
                    "    bnb_4bit_quant_type='nf4',\n",
                    "    bnb_4bit_compute_dtype=torch.float16\n",
                    ")\n",
                    "\n",
                    "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)\n",
                    "tokenizer.pad_token = tokenizer.eos_token\n",
                    "\n",
                    "model = AutoModelForCausalLM.from_pretrained(\n",
                    "    MODEL_ID,\n",
                    "    quantization_config=bnb_config,\n",
                    "    device_map='auto',\n",
                    "    trust_remote_code=True\n",
                    ")\n",
                    "\n",
                    "peft_config = LoraConfig(\n",
                    "    task_type=TaskType.CAUSAL_LM,\n",
                    "    r=16,\n",
                    "    lora_alpha=32,\n",
                    "    lora_dropout=0.05,\n",
                    "    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj']\n",
                    ")\n",
                    "\n",
                    "model = get_peft_model(model, peft_config)\n",
                    "dataset = load_dataset('json', data_files={'train': 'train.jsonl'})['train']\n",
                    "\n",
                    "def format_prompts(batch):\n",
                    "    texts = []\n",
                    "    for instr, inp, out in zip(batch['instruction'], batch.get('input_context', ['']*len(batch['instruction'])), batch['output']):\n",
                    "        text = f'<|im_start|>user\\n{instr}\\n{inp}<|im_end|>\\n<|im_start|>assistant\\n{out}<|im_end|>'\n",
                    "        texts.append(text)\n",
                    "    return {'text': texts}\n",
                    "\n",
                    "dataset = dataset.map(format_prompts, batched=True)\n",
                    "\n",
                    "args = TrainingArguments(\n",
                    "    output_dir='./results',\n",
                    "    per_device_train_batch_size=4,\n",
                    "    gradient_accumulation_steps=2,\n",
                    "    num_train_epochs=3,\n",
                    "    learning_rate=2e-4,\n",
                    "    fp16=True,\n",
                    "    logging_steps=10,\n",
                    "    save_strategy='no'\n",
                    ")\n",
                    "\n",
                    "trainer = SFTTrainer(\n",
                    "    model=model,\n",
                    "    train_dataset=dataset,\n",
                    "    dataset_text_field='text',\n",
                    "    max_seq_length=512,\n",
                    "    args=args\n",
                    ")\n",
                    "trainer.train()"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 4. Merge LoRA weights & Convert to GGUF\n",
                    "model = model.merge_and_unload()\n",
                    "merged_dir = './merged_model'\n",
                    "model.save_pretrained(merged_dir)\n",
                    "tokenizer.save_pretrained(merged_dir)\n",
                    "\n",
                    f"output_gguf = '{expert_name}.gguf'\n",
                    "# Use llama.cpp script to convert to GGUF\n",
                    "!python /tmp/llama_cpp/convert_hf_to_gguf.py ./merged_model --outfile {output_gguf} --outtype q4_k_m\n",
                    "print(f'GGUF export ready: {output_gguf}')\n",
                    "files.download(output_gguf)"
                ]
            }
        ],
        "metadata": {
            "accelerator": "GPU",
            "colab": {
                "gpuType": "T4",
                "provenance": []
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)
    print(f"[SUCCESS] Generated runnable Colab Notebook at: {output_path}")

def main():
    args = parse_args()
    dataset_path = Path(args.dataset_dir)
    output_nb = Path(args.output_notebook)
    
    print(f"=== Xavier Colab CLI Pipeline ===")
    print(f"Dataset Dir: {dataset_path}")
    print(f"Output Notebook: {output_nb}")
    print(f"Target Expert: {args.target_expert}")
    print(f"Base Model: {args.base_model}")
    
    if args.check_audit and dataset_path.exists():
        verify_anonymization_audit(dataset_path)
        
    generate_colab_notebook(output_nb, args.base_model, args.target_expert)

if __name__ == "__main__":
    main()
