#!/usr/bin/env bash
# Build the Xavier desktop shell natively on NixOS and install a double-click
# launcher. Idempotent. Store paths are resolved at run time (nothing hardcoded);
# they are pinned with GC roots so `nix-collect-garbage` cannot break the app.
#
# Usage: scripts/desktop/install-nixos.sh [--no-build]
#   CARGO_TARGET_DIR  build output (default: <repo>/target)
#   PREFIX            install prefix for bin/ and libexec/ (default: ~/.local)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
TARGET="${CARGO_TARGET_DIR:-$REPO/target}"
ROOTS="$DATA/xavier-desktop/gcroots"
LIBEXEC="$PREFIX/libexec/xavier-desktop"
LAUNCHER="$PREFIX/bin/xavier-desktop"
TAURI="$REPO/panel-ui/src-tauri"
STAMP="$(date +%Y%m%d-%H%M%S)"

command -v nix-shell >/dev/null || { echo "nix-shell not found (NixOS only)" >&2; exit 1; }

# 1. Build (frontend + shell) inside the repo's nix-shell.
if [ "${1:-}" != "--no-build" ]; then
  TRIPLE="$(rustc -Vv | sed -n 's/^host: //p')"
  SIDECAR="$TAURI/binaries/xavier-$TRIPLE"
  mkdir -p "$TAURI/binaries"
  if [ ! -e "$SIDECAR" ]; then
    # The shell attaches to a running Xavier; the sidecar is only a fallback.
    if [ -x "$PREFIX/bin/xavier" ]; then ln -s "$PREFIX/bin/xavier" "$SIDECAR"
    else printf '#!/bin/sh\nexit 1\n' >"$SIDECAR"; chmod +x "$SIDECAR"; fi
  fi
  (cd "$REPO" && pnpm install --no-frozen-lockfile --config.dangerouslyAllowAllBuilds=true)
  (cd "$REPO" && CARGO_TARGET_DIR="$TARGET" nice -n 19 \
    nix-shell shell.nix --run 'cd panel-ui && pnpm exec tauri build --no-bundle')
fi
BIN="$TARGET/release/xavier-desktop"
[ -x "$BIN" ] || { echo "missing $BIN (run without --no-build)" >&2; exit 1; }

# 2. Resolve runtime dependencies and pin them (same <nixpkgs> as shell.nix).
mkdir -p "$ROOTS"
resolve() { nix-build '<nixpkgs>' -A "$1" -o "$ROOTS/$1" >/dev/null && readlink -f "$ROOTS/$1"; }
GTK3="$(resolve gtk3)"; APPIND="$(resolve libayatana-appindicator)"
GNET="$(resolve glib-networking)"; GSET="$(resolve gsettings-desktop-schemas)"
MIME="$(resolve shared-mime-info)"; ICONS="$(resolve adwaita-icon-theme)"
RSVG="$(resolve librsvg)"
# Pin the libraries the binary links against (webkitgtk, gtk, ...) too.
ldd "$BIN" | awk '/\/nix\/store\//{print $3}' | sed -E 's#^(/nix/store/[^/]+)/.*#\1#' | sort -u |
  while read -r p; do nix-store --add-root "$ROOTS/link-$(basename "$p")" --indirect -r "$p" >/dev/null; done

# 3. Install binary (backing up any previous launcher) and the wrapper.
mkdir -p "$LIBEXEC" "$PREFIX/bin"
if [ -e "$LAUNCHER" ] && ! grep -q 'xavier-desktop-wrapper' "$LAUNCHER" 2>/dev/null; then
  cp -a "$LAUNCHER" "$LAUNCHER.bak-$STAMP"
fi
install -m 0755 "$BIN" "$LIBEXEC/xavier-desktop"
cat >"$LAUNCHER" <<WRAP
#!/usr/bin/env bash
# xavier-desktop-wrapper: generated by scripts/desktop/install-nixos.sh - do not edit.
export LD_LIBRARY_PATH="$APPIND/lib:/run/opengl-driver/lib\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="$(ls -d "$GTK3"/share/gsettings-schemas/*):$(ls -d "$GSET"/share/gsettings-schemas/*):$ICONS/share:$MIME/share\${XDG_DATA_DIRS:+:\$XDG_DATA_DIRS}:/run/current-system/sw/share"
export GIO_MODULE_DIR="$GNET/lib/gio/modules"
export GDK_PIXBUF_MODULE_FILE="$(ls "$RSVG"/lib/gdk-pixbuf-*/*/loaders.cache 2>/dev/null | head -n1)"
[ -n "\$GDK_PIXBUF_MODULE_FILE" ] || unset GDK_PIXBUF_MODULE_FILE
exec -a xavier-desktop "$LIBEXEC/xavier-desktop" "\$@"
WRAP
chmod 0755 "$LAUNCHER"

# 4. Icons and desktop entry.
for pair in 32:32x32 64:64x64 128:128x128 256:128x128@2x 512:icon; do
  size="${pair%%:*}"; src="$TAURI/icons/${pair#*:}.png"
  d="$DATA/icons/hicolor/${size}x${size}/apps"; mkdir -p "$d"; install -m 0644 "$src" "$d/xavier.png"
done
mkdir -p "$DATA/applications"
cat >"$DATA/applications/xavier.desktop" <<DESK
[Desktop Entry]
Type=Application
Name=Xavier
Comment=Cognitive memory for AI agents
Exec=$LAUNCHER
Icon=xavier
Terminal=false
Categories=Development;Utility;
StartupWMClass=xavier-desktop
DESK
command -v update-desktop-database >/dev/null && update-desktop-database "$DATA/applications" || true
command -v gtk-update-icon-cache >/dev/null && gtk-update-icon-cache -q -t "$DATA/icons/hicolor" || true

echo "Installed: $LAUNCHER (binary: $LIBEXEC/xavier-desktop)"
echo "Desktop entry: $DATA/applications/xavier.desktop"
