[build]
target-dir = "./target"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"] # Commented out (causes Bus error in CI runners)

# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[env]
RUST_MIN_STACK = "16777216"
