//! Chronicle static site generator integration
//!
//! Provides the implementation and data structures for this module's
//! responsibilities within the Xavier cognitive memory system.
use anyhow::{Context, Result};
use pulldown_cmark::{html, Options, Parser};
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

#[derive(Clone)]
pub struct PostMetadata {
    pub title: String,
    pub date: String,
    pub slug: String,
    pub tags: Vec<String>,
    pub description: String,
}

pub struct DevLogSSG {
    input_dir: PathBuf,
    output_dir: PathBuf,
}

const HTML_TEMPLATE: &str = r##"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}} — Xavier DevLog</title>
    <meta name="description" content="{{description}}">
    <meta property="og:title" content="{{title}} — Xavier DevLog">
    <meta property="og:description" content="{{description}}">
    <meta property="og:type" content="article">
    <meta name="color-scheme" content="dark light">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <a href="#main-content" class="skip-link">Skip to content</a>
    <header class="site-header">
        <div class="container header-inner">
            <div class="logo-area">
                <h1 class="site-title"><a href="index.html">Xavier DevLog</a></h1>
                <p class="tagline">Cognitive Memory Runtime — Technical Logs</p>
            </div>
            <nav class="site-nav" aria-label="Main navigation">
                <a href="index.html" class="nav-link">DevLog</a>
                <a href="https://southwest-ai-labs.github.io/xavier/" class="nav-link" target="_blank" rel="noopener">Docs</a>
                <a href="https://github.com/iberi22/xavier" class="nav-link" target="_blank" rel="noopener">GitHub</a>
                <button id="theme-toggle" class="theme-toggle" aria-label="Toggle dark/light mode">
                    <span class="icon-light">&#9728;</span>
                    <span class="icon-dark">&#9790;</span>
                </button>
            </nav>
        </div>
    </header>

    <main id="main-content" class="container main-content">
        {{content}}
    </main>

    <footer class="site-footer">
        <div class="container footer-inner">
            <p>&copy; 2026 Xavier Project. Generated by <a href="https://github.com/iberi22/xavier">Xavier Chronicle SSG</a>.</p>
            <p class="footer-links">
                <a href="https://github.com/iberi22/xavier" target="_blank" rel="noopener">GitHub</a>
                <span class="sep">.</span>
                <a href="https://southwest-ai-labs.github.io/xavier/" target="_blank" rel="noopener">Documentation</a>
            </p>
        </div>
    </footer>
    <script src="main.js"></script>
</body>
</html>"##;

const CSS_ASSET: &str = r##"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
:root {
    --bg: #ffffff;
    --bg-alt: #f6f8fa;
    --surface: #ffffff;
    --surface-alt: #f0f2f5;
    --text: #1f2328;
    --text-secondary: #656d76;
    --text-tertiary: #8b949e;
    --accent: #0969da;
    --accent-hover: #0550ae;
    --border: #d0d7de;
    --border-light: #e8ecef;
    --header-bg: #0d1117;
    --header-text: #e6edf3;
    --header-accent: #58a6ff;
    --code-bg: #f0f2f5;
    --code-text: #1f2328;
    --pre-bg: #0d1117;
    --pre-text: #e6edf3;
    --tag-bg: #ddf4ff;
    --tag-text: #0969da;
    --success: #1a7f37;
    --warning: #9a6700;
    --max-width: 960px;
    --radius: 8px;
    --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif;
    --font-mono: "SF Mono", "Fira Code", "Cascadia Code", "JetBrains Mono", Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
    :root { --bg: #0d1117; --bg-alt: #151b23; --surface: #151b23;
        --surface-alt: #21262d; --text: #e6edf3; --text-secondary: #8b949e;
        --text-tertiary: #6e7681; --accent: #58a6ff; --accent-hover: #79c0ff;
        --border: #30363d; --border-light: #21262d;
        --header-bg: #010409; --header-text: #e6edf3; --header-accent: #58a6ff;
        --code-bg: #161b22; --code-text: #e6edf3; --pre-bg: #010409; --pre-text: #e6edf3;
        --tag-bg: #0d419d; --tag-text: #58a6ff; --success: #3fb950; --warning: #d29922; }
}
[data-theme="light"] { --bg: #ffffff; --bg-alt: #f6f8fa; --surface: #ffffff;
    --surface-alt: #f0f2f5; --text: #1f2328; --text-secondary: #656d76;
    --accent: #0969da; --accent-hover: #0550ae; --border: #d0d7de; --border-light: #e8ecef;
    --header-bg: #0d1117; --header-text: #e6edf3; --header-accent: #58a6ff;
    --code-bg: #f0f2f5; --code-text: #1f2328; --pre-bg: #0d1117; --pre-text: #e6edf3;
    --tag-bg: #ddf4ff; --tag-text: #0969da; }
[data-theme="dark"] { --bg: #0d1117; --bg-alt: #151b23; --surface: #151b23;
    --surface-alt: #21262d; --text: #e6edf3; --text-secondary: #8b949e;
    --accent: #58a6ff; --accent-hover: #79c0ff; --border: #30363d; --border-light: #21262d;
    --header-bg: #010409; --header-text: #e6edf3; --header-accent: #58a6ff;
    --code-bg: #161b22; --code-text: #e6edf3; --pre-bg: #010409; --pre-text: #e6edf3;
    --tag-bg: #0d419d; --tag-text: #58a6ff; --success: #3fb950; --warning: #d29922; }
body {
    font-family: var(--font-sans); background: var(--bg); color: var(--text);
    line-height: 1.6; -webkit-font-smoothing: antialiased;
    min-height: 100vh; display: flex; flex-direction: column;
}
.container { max-width: var(--max-width); margin: 0 auto; padding: 0 24px; width: 100%; }
.skip-link { position: absolute; top: -100%; left: 8px; z-index: 100;
    background: var(--accent); color: #fff; padding: 8px 16px; border-radius: 4px;
    text-decoration: none; font-weight: 600; }
.skip-link:focus { top: 8px; }
.site-header { background: var(--header-bg); border-bottom: 1px solid var(--border);
    padding: 16px 0; position: sticky; top: 0; z-index: 50; }
.header-inner { display: flex; align-items: center; justify-content: space-between; gap: 16px; flex-wrap: wrap; }
.logo-area { flex-shrink: 0; }
.site-title { font-size: 1.4rem; font-weight: 700; letter-spacing: -0.02em; }
.site-title a { color: var(--header-text); text-decoration: none; }
.site-title a:hover { color: var(--header-accent); }
.tagline { font-size: 0.8rem; color: var(--text-tertiary); margin-top: 0; }
.site-nav { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
.nav-link { color: var(--text-tertiary); text-decoration: none; font-size: 0.9rem;
    padding: 6px 12px; border-radius: 6px; transition: all .15s; }
.nav-link:hover { color: var(--header-text); background: var(--surface-alt); }
.theme-toggle { background: none; border: 1px solid var(--border); border-radius: 6px;
    cursor: pointer; padding: 4px 8px; font-size: 1rem; line-height: 1;
    color: var(--text-tertiary); transition: all .15s; margin-left: 4px; }
.theme-toggle:hover { border-color: var(--header-accent); color: var(--header-accent); }
[data-theme="dark"] .icon-light, [data-theme="light"] .icon-dark { display: none; }
[data-theme="dark"] .icon-dark, [data-theme="light"] .icon-light { display: inline; }
@media (prefers-color-scheme: dark) { .icon-light { display: none; } .icon-dark { display: inline; } }
@media (prefers-color-scheme: light) { .icon-dark { display: none; } .icon-light { display: inline; } }
.main-content { flex: 1; padding-top: 32px; padding-bottom: 64px; }
.breadcrumbs { font-size: 0.85rem; color: var(--text-secondary); margin-bottom: 16px;
    padding-bottom: 12px; border-bottom: 1px solid var(--border-light); }
.breadcrumbs a { color: var(--accent); text-decoration: none; }
.breadcrumbs a:hover { text-decoration: underline; }
.breadcrumbs .sep { margin: 0 6px; color: var(--text-tertiary); }
.breadcrumbs .current { color: var(--text-secondary); }
article.post { background: var(--surface); border: 1px solid var(--border);
    border-radius: var(--radius); padding: 40px; margin-bottom: 32px; }
article.post h1 { font-size: 2rem; font-weight: 700; letter-spacing: -0.02em;
    line-height: 1.3; margin-bottom: 16px; color: var(--text); }
.post-meta { display: flex; flex-wrap: wrap; gap: 12px; align-items: center;
    margin-bottom: 24px; padding-bottom: 20px; border-bottom: 1px solid var(--border-light);
    font-size: 0.9rem; color: var(--text-secondary); }
.post-date { white-space: nowrap; }
.post-tags { display: flex; gap: 6px; flex-wrap: wrap; }
.post-tag { display: inline-block; padding: 2px 8px; border-radius: 12px;
    background: var(--tag-bg); color: var(--tag-text); font-size: 0.8rem; font-weight: 500; }
.post-body { font-size: 1rem; line-height: 1.7; }
.post-body h2 { font-size: 1.5rem; font-weight: 600; margin-top: 32px; margin-bottom: 16px;
    padding-bottom: 8px; border-bottom: 1px solid var(--border-light); color: var(--text); }
.post-body h3 { font-size: 1.2rem; font-weight: 600; margin-top: 24px; margin-bottom: 12px; color: var(--text); }
.post-body h4 { font-size: 1.05rem; font-weight: 600; margin-top: 20px; margin-bottom: 8px; }
.post-body p { margin-bottom: 16px; }
.post-body a { color: var(--accent); text-decoration: none; }
.post-body a:hover { text-decoration: underline; }
.post-body ul, .post-body ol { margin-bottom: 16px; padding-left: 24px; }
.post-body li { margin-bottom: 6px; }
.post-body strong { font-weight: 600; }
.post-body blockquote { margin: 16px 0; padding: 12px 20px; border-left: 4px solid var(--accent);
    background: var(--bg-alt); border-radius: 0 var(--radius) var(--radius) 0;
    color: var(--text-secondary); }
.post-body hr { border: none; border-top: 1px solid var(--border-light); margin: 32px 0; }
.post-body img { max-width: 100%; border-radius: var(--radius); margin: 16px 0; }
.post-body table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 0.95rem; }
.post-body th, .post-body td { padding: 10px 14px; border: 1px solid var(--border); text-align: left; }
.post-body th { background: var(--bg-alt); font-weight: 600; }
.post-body tr:nth-child(even) { background: var(--bg-alt); }
.post-body code { font-family: var(--font-mono); font-size: 0.85em;
    background: var(--code-bg); color: var(--code-text); padding: 2px 6px; border-radius: 4px; }
.post-body pre { background: var(--pre-bg); color: var(--pre-text); padding: 20px;
    border-radius: var(--radius); overflow-x: auto; margin: 16px 0;
    border: 1px solid var(--border); font-size: 0.85rem; line-height: 1.5; }
.post-body pre code { background: none; color: inherit; padding: 0; font-size: inherit; border-radius: 0; }
.search-box { width: 100%; padding: 12px 16px; border: 1px solid var(--border);
    border-radius: var(--radius); background: var(--surface); color: var(--text);
    font-size: 0.95rem; margin-bottom: 24px; transition: border-color .15s; }
.search-box:focus { outline: none; border-color: var(--accent); box-shadow: 0 0 0 3px rgba(9,105,218,.15); }
.search-box::placeholder { color: var(--text-tertiary); }
.post-list { list-style: none; padding: 0; }
.post-list li { display: flex; align-items: baseline; gap: 12px;
    padding: 14px 0; border-bottom: 1px solid var(--border-light); }
.post-list li:last-child { border-bottom: none; }
.post-list .post-date { font-family: var(--font-mono); font-size: 0.85rem;
    color: var(--text-tertiary); white-space: nowrap; min-width: 88px; flex-shrink: 0; }
.post-list .post-title-wrap { flex: 1; min-width: 0; }
.post-list .post-title { font-size: 1.05rem; font-weight: 500; color: var(--text);
    text-decoration: none; line-height: 1.4; }
.post-list .post-title:hover { color: var(--accent); }
.post-list .post-desc { font-size: 0.85rem; color: var(--text-secondary);
    margin-top: 2px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.post-list .post-tags-inline { display: inline-flex; gap: 4px; margin-left: 8px; flex-shrink: 0; }
.tag-mini { font-size: 0.7rem; padding: 1px 6px; border-radius: 8px;
    background: var(--tag-bg); color: var(--tag-text); }
.empty-state { text-align: center; padding: 48px 24px; color: var(--text-secondary); }
.empty-state p { font-size: 1.1rem; }
.empty-state .hint { font-size: 0.9rem; margin-top: 8px; color: var(--text-tertiary); }
.site-footer { background: var(--bg-alt); border-top: 1px solid var(--border);
    padding: 24px 0; margin-top: auto; font-size: 0.85rem; color: var(--text-secondary); }
.footer-inner { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 8px; }
.site-footer a { color: var(--accent); text-decoration: none; }
.site-footer a:hover { text-decoration: underline; }
.footer-links .sep { margin: 0 6px; color: var(--text-tertiary); }
@media (max-width: 768px) { .header-inner { flex-direction: column; align-items: flex-start; }
    .site-nav { width: 100%; justify-content: flex-start; }
    article.post { padding: 24px; }
    .post-list li { flex-direction: column; gap: 4px; }
    .post-list .post-date { min-width: auto; }
    .post-list .post-tags-inline { margin-left: 0; }
    .post-body { font-size: 0.95rem; }
    article.post h1 { font-size: 1.6rem; }
    .footer-inner { flex-direction: column; text-align: center; } }
"##;

const JS_ASSET: &str = r##"(function() {
    'use strict';
    function getPreferredTheme() {
        var stored = localStorage.getItem('xavier-theme');
        if (stored) return stored;
        return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }
    function setTheme(theme) {
        document.documentElement.setAttribute('data-theme', theme);
        localStorage.setItem('xavier-theme', theme);
    }
    setTheme(getPreferredTheme());
    var toggleBtn = document.getElementById('theme-toggle');
    if (toggleBtn) {
        toggleBtn.addEventListener('click', function() {
            var current = document.documentElement.getAttribute('data-theme');
            setTheme(current === 'dark' ? 'light' : 'dark');
        });
    }
    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', function(e) {
        if (!localStorage.getItem('xavier-theme')) {
            setTheme(e.matches ? 'dark' : 'light');
        }
    });
    var searchInput = document.getElementById('post-search');
    var postList = document.getElementById('post-list');
    if (searchInput && postList) {
        var items = postList.querySelectorAll('li');
        var noResults = document.getElementById('no-results');
        searchInput.addEventListener('input', function() {
            var query = this.value.toLowerCase().trim();
            var visibleCount = 0;
            items.forEach(function(item) {
                var title = item.querySelector('.post-title');
                var desc = item.querySelector('.post-desc');
                var tags = item.querySelector('.post-tags-inline');
                var text = (title ? title.textContent : '') + ' ' +
                           (desc ? desc.textContent : '') + ' ' +
                           (tags ? tags.textContent : '');
                var matches = !query || text.toLowerCase().includes(query);
                item.style.display = matches ? '' : 'none';
                if (matches) visibleCount++;
            });
            if (noResults) {
                noResults.style.display = visibleCount === 0 ? 'block' : 'none';
            }
        });
    }
    console.log('Xavier DevLog loaded.');
})();
"##;

/// Names of files that should not be treated as blog posts
const SKIP_FILES: &[&str] = &["INDEX.md", "README.md", "index.md", "readme.md"];

impl Default for DevLogSSG {
    fn default() -> Self {
        Self::new()
    }
}

impl DevLogSSG {
    pub fn new() -> Self {
        Self {
            input_dir: PathBuf::from("docs/devlog"),
            output_dir: PathBuf::from("public/devlog"),
        }
    }

    pub fn build(&self) -> Result<()> {
        println!("Building DevLog SSG...");

        if !self.input_dir.exists() {
            fs::create_dir_all(&self.input_dir)?;
            println!("Created input directory: {}", self.input_dir.display());
        }

        // Clean output directory to remove stale files
        if self.output_dir.exists() {
            fs::remove_dir_all(&self.output_dir).with_context(|| {
                format!("Failed to clean output dir: {}", self.output_dir.display())
            })?;
            println!("Cleaned output directory: {}", self.output_dir.display());
        }

        if !self.output_dir.exists() {
            fs::create_dir_all(&self.output_dir)?;
            println!("Created output directory: {}", self.output_dir.display());
        }

        fs::write(self.output_dir.join("style.css"), CSS_ASSET)?;
        fs::write(self.output_dir.join("main.js"), JS_ASSET)?;

        let post_paths = self.discover_posts()?;
        println!("Found {} posts", post_paths.len());

        let mut posts_metadata = Vec::new();

        for path in &post_paths {
            let metadata = self.process_post(path)?;
            posts_metadata.push(metadata);
        }

        self.generate_index(&posts_metadata)?;

        Ok(())
    }

    fn process_post(&self, path: &Path) -> Result<PostMetadata> {
        let content = fs::read_to_string(path)
            .with_context(|| format!("Failed to read post: {}", path.display()))?;

        let filename = path
            .file_stem()
            .expect("file must have a stem")
            .to_str()
            .expect("filename must be valid UTF-8");

        let metadata = Self::extract_metadata(&content, filename);

        let html_content = self.render_markdown(&content);

        // Build post HTML
        let tags_html = if metadata.tags.is_empty() {
            String::new()
        } else {
            let tag_links: Vec<String> = metadata
                .tags
                .iter()
                .map(|t| format!(r#"<span class="post-tag">{}</span>"#, html_escape(t)))
                .collect();
            format!(r#"<div class="post-tags">{}</div>"#, tag_links.join(""))
        };

        let breadcrumbs = format!(
            r#"<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">DevLog</a><span class="sep">/</span><span class="current">{}</span></nav>"#,
            html_escape(&metadata.title)
        );

        let article_html = format!(
            r##"<article class="post">
                {breadcrumbs}
                <h1>{title}</h1>
                <div class="post-meta">
                    <span class="post-date">{date}</span>
                    {tags_html}
                </div>
                <div class="post-body">
                    {content}
                </div>
            </article>"##,
            breadcrumbs = breadcrumbs,
            title = html_escape(&metadata.title),
            date = html_escape(&metadata.date),
            tags_html = tags_html,
            content = html_content,
        );

        let full_html = HTML_TEMPLATE
            .replace("{{title}}", &metadata.title)
            .replace("{{description}}", &metadata.description)
            .replace("{{content}}", &article_html);

        let output_filename = format!("{}.html", filename);
        let output_path = self.output_dir.join(output_filename);

        fs::write(&output_path, full_html)
            .with_context(|| format!("Failed to write HTML: {}", output_path.display()))?;

        Ok(metadata)
    }

    /// Pure function: extract metadata from markdown content without side effects.
    /// This is testable without creating files.
    fn extract_metadata(content: &str, filename: &str) -> PostMetadata {
        // Extract title from first # header
        let title = content
            .lines()
            .find(|l| l.starts_with("# "))
            .map(|l| l.trim_start_matches("# ").trim().to_string())
            .unwrap_or_else(|| filename.to_string());

        // Extract date from filename (expecting YYYY-MM-DD-...)
        let date = if filename.len() >= 10
            && filename.as_bytes()[4] == b'-'
            && filename.as_bytes()[7] == b'-'
        {
            filename[0..10].to_string()
        } else {
            // Fallback: try to find a date line in the content
            let date_line = content
                .lines()
                .find(|l| {
                    let trimmed = l.trim();
                    trimmed.starts_with("**Date**")
                        || trimmed.starts_with("Date:")
                        || trimmed.starts_with("date:")
                })
                .map(|l| {
                    let cleaned = l
                        .trim_start_matches("**Date**")
                        .trim_start_matches("Date:")
                        .trim_start_matches("date:")
                        .trim()
                        .trim_matches(|c: char| c == '*' || c == ':' || c == ' ');
                    cleaned.to_string()
                });
            date_line.unwrap_or_else(|| chrono::Utc::now().format("%Y-%m-%d").to_string())
        };

        // Extract tags from content
        let tags = content
            .lines()
            .find(|l| {
                let trimmed = l.trim();
                trimmed.starts_with("**Tags**")
                    || trimmed.starts_with("Tags:")
                    || trimmed.starts_with("tags:")
            })
            .map(|l| {
                let cleaned = l
                    .trim_start_matches("**Tags**")
                    .trim_start_matches("Tags:")
                    .trim_start_matches("tags:")
                    .trim()
                    .trim_matches(|c: char| c == '*' || c == ':' || c == ' ');
                cleaned
                    .trim_start_matches('[')
                    .trim_end_matches(']')
                    .split(',')
                    .map(|t| t.trim().trim_matches('"').trim_matches('\'').to_string())
                    .filter(|t| !t.is_empty())
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();

        // Extract description (first paragraph after the title)
        let description = content
            .lines()
            .skip_while(|l| !l.starts_with("# "))
            .skip(1)
            .find(|l| {
                let trimmed = l.trim();
                !trimmed.is_empty()
                    && !trimmed.starts_with("**")
                    && !trimmed.starts_with("---")
                    && !trimmed.starts_with('<')
                    && !trimmed.starts_with("##")
            })
            .map(|l| l.trim().to_string())
            .unwrap_or_default();

        PostMetadata {
            title,
            date,
            slug: format!("{}.html", filename),
            tags,
            description,
        }
    }

    fn generate_index(&self, posts: &[PostMetadata]) -> Result<()> {
        let mut sorted_posts = posts.to_vec();
        sorted_posts.sort_by(|a, b| b.date.cmp(&a.date));

        let mut posts_list = String::new();

        for post in &sorted_posts {
            let tags_html: String = if post.tags.is_empty() {
                String::new()
            } else {
                let mini_tags: Vec<String> = post
                    .tags
                    .iter()
                    .map(|t| format!(r#"<span class="tag-mini">{}</span>"#, html_escape(t)))
                    .collect();
                format!(
                    r#"<span class="post-tags-inline">{}</span>"#,
                    mini_tags.join("")
                )
            };

            let desc_html = if post.description.is_empty() {
                String::new()
            } else {
                format!(
                    r#"<div class="post-desc">{}</div>"#,
                    html_escape(&post.description)
                )
            };

            posts_list.push_str(&format!(
                r#"<li>
                    <span class="post-date">{date}</span>
                    <div class="post-title-wrap">
                        <a href="{slug}" class="post-title">{title}</a>
                        {desc}
                        {tags}
                    </div>
                </li>"#,
                date = html_escape(&post.date),
                slug = html_escape(&post.slug),
                title = html_escape(&post.title),
                desc = desc_html,
                tags = tags_html,
            ));
        }

        let content = format!(
            r##"<h1>Technical Logs</h1>
                <p style="color: var(--text-secondary); font-size: 1.05rem; margin-bottom: 24px;">
                Deep-dive technical narratives about Xavier architecture, decisions, and internals.</p>
                <input type="search" id="post-search" class="search-box"
                       placeholder="Search posts by title, tag, or keyword..." aria-label="Search posts">
                <ul class="post-list" id="post-list">
                    {posts}
                </ul>
                <div id="no-results" class="empty-state" style="display:none;">
                    <p>No posts match your search.</p>
                    <p class="hint">Try a different keyword or browse all posts above.</p>
                </div>"##,
            posts = posts_list,
        );

        let index_html = HTML_TEMPLATE
            .replace("{{title}}", "DevLog")
            .replace("{{description}}", "Xavier Cognitive Memory Runtime - Technical deep-dive narratives about architecture, decisions, and internals.")
            .replace("{{content}}", &content);

        let output_path = self.output_dir.join("index.html");
        fs::write(&output_path, index_html)
            .with_context(|| format!("Failed to write index.html: {}", output_path.display()))?;

        Ok(())
    }

    fn render_markdown(&self, markdown: &str) -> String {
        let mut options = Options::empty();
        options.insert(Options::ENABLE_TABLES);
        options.insert(Options::ENABLE_FOOTNOTES);
        options.insert(Options::ENABLE_STRIKETHROUGH);
        options.insert(Options::ENABLE_TASKLISTS);
        options.insert(Options::ENABLE_HEADING_ATTRIBUTES);

        let parser = Parser::new_ext(markdown, options);
        let mut html_output = String::new();
        html::push_html(&mut html_output, parser);
        html_output
    }

    fn discover_posts(&self) -> Result<Vec<PathBuf>> {
        let mut posts = Vec::new();
        for entry in WalkDir::new(&self.input_dir).max_depth(1) {
            let entry = entry?;
            let path = entry.path();
            if path.is_file() && path.extension().is_some_and(|ext| ext == "md") {
                let filename = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
                if SKIP_FILES
                    .iter()
                    .any(|s| s.eq_ignore_ascii_case(filename))
                {
                    continue;
                }
                posts.push(path.to_path_buf());
            }
        }
        posts.sort();
        Ok(posts)
    }
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_render_markdown() {
        let ssg = DevLogSSG::new();
        let html = ssg.render_markdown("# Hello\nWorld");
        assert!(html.contains("<h1>Hello</h1>"));
        assert!(html.contains("<p>World</p>"));
    }

    #[test]
    fn test_ssg_build() -> Result<()> {
        let input_dir = tempdir()?;
        let output_dir = tempdir()?;
        let ssg = DevLogSSG {
            input_dir: input_dir.path().to_path_buf(),
            output_dir: output_dir.path().to_path_buf(),
        };
        fs::write(
            input_dir.path().join("2024-05-20-test.md"),
            "# Test\nContent",
        )?;
        ssg.build()?;
        assert!(output_dir.path().join("index.html").exists());
        assert!(output_dir.path().join("2024-05-20-test.html").exists());
        assert!(output_dir.path().join("style.css").exists());
        assert!(output_dir.path().join("main.js").exists());
        let index_content = fs::read_to_string(output_dir.path().join("index.html"))?;
        assert!(index_content.contains("2024-05-20"));
        Ok(())
    }

    #[test]
    fn test_skip_non_post_files() -> Result<()> {
        let input_dir = tempdir()?;
        let output_dir = tempdir()?;
        fs::write(input_dir.path().join("INDEX.md"), "# Index")?;
        fs::write(input_dir.path().join("README.md"), "# Readme")?;
        fs::write(
            input_dir.path().join("2026-05-10-real-post.md"),
            "# Real Post",
        )?;
        let ssg = DevLogSSG {
            input_dir: input_dir.path().to_path_buf(),
            output_dir: output_dir.path().to_path_buf(),
        };
        ssg.build()?;

        // On case-insensitive filesystems, INDEX.html and index.html are the same file.
        // Since the SSG always generates index.html, we cannot assert INDEX.html does not exist.
        // We skip INDEX.html check and focus on other non-post files.
        assert!(!output_dir.path().join("README.html").exists());
        assert!(!output_dir.path().join("index.md.html").exists());
        assert!(!output_dir.path().join("readme.md.html").exists());
        assert!(output_dir.path().join("2026-05-10-real-post.html").exists());

        let index_content = fs::read_to_string(output_dir.path().join("index.html"))?;
        assert!(index_content.contains("Real Post"));

        // Verify skipped files are not in the index list
        assert!(!index_content.contains(">Index<"));
        assert!(!index_content.contains(">Readme<"));
        Ok(())
    }

    #[test]
    fn test_extract_title_from_content() {
        let meta = DevLogSSG::extract_metadata("# My Awesome Title\nContent here", "test.md");
        assert_eq!(meta.title, "My Awesome Title");
    }

    #[test]
    fn test_extract_date_from_filename() {
        let meta = DevLogSSG::extract_metadata("# Title", "2026-05-15-important-update.md");
        assert_eq!(meta.date, "2026-05-15");
    }

    #[test]
    fn test_extract_tags_from_content() {
        let meta = DevLogSSG::extract_metadata(
            "# Tagged Post\n**Tags**: [rust, architecture, memory]\n\nContent.",
            "2026-05-15-tagged.md",
        );
        assert!(meta.tags.contains(&"rust".to_string()));
        assert!(meta.tags.contains(&"architecture".to_string()));
        assert_eq!(meta.tags.len(), 3);
    }

    #[test]
    fn test_extract_description() {
        let meta = DevLogSSG::extract_metadata(
            "# Post\n**Tags**: [test]\n\nThis is the first paragraph that should be the description.\n\nSecond paragraph.",
            "2026-05-15-desc.md",
        );
        assert!(meta.description.contains("first paragraph"));
    }

    #[test]
    fn test_html_escape() {
        assert_eq!(html_escape("hello & world"), "hello &amp; world");
        assert_eq!(html_escape("<script>"), "&lt;script&gt;");
        assert_eq!(html_escape("\"quoted\""), "&quot;quoted&quot;");
        assert_eq!(html_escape("it's"), "it&#39;s");
    }

    #[test]
    fn test_breadcrumbs_in_processed_post() {
        let meta = DevLogSSG::extract_metadata("# Breadcrumb Test", "2026-05-15-breadcrumb");
        assert_eq!(meta.slug, "2026-05-15-breadcrumb.html");
    }

    #[test]
    fn test_post_date_fallback_from_content() {
        let meta = DevLogSSG::extract_metadata(
            "# My Post\n**Date**: 2026-05-20\n**Tags**: [test]\n\nContent.",
            "my-post",
        );
        assert_eq!(meta.date, "2026-05-20");
    }

    #[test]
    fn test_tags_empty_when_no_tags() {
        let meta = DevLogSSG::extract_metadata("# No Tags", "2026-05-15-no-tags");
        assert!(meta.tags.is_empty());
    }

    #[test]
    fn test_index_sorts_posts_by_date_desc() {
        let _ssg = DevLogSSG::new();
        let posts = vec![
            PostMetadata {
                title: "Old".into(),
                date: "2026-05-01".into(),
                slug: "old.html".into(),
                tags: vec![],
                description: String::new(),
            },
            PostMetadata {
                title: "New".into(),
                date: "2026-05-15".into(),
                slug: "new.html".into(),
                tags: vec![],
                description: String::new(),
            },
            PostMetadata {
                title: "Middle".into(),
                date: "2026-05-10".into(),
                slug: "middle.html".into(),
                tags: vec![],
                description: String::new(),
            },
        ];
        let dir = tempdir().unwrap();
        let ssg = DevLogSSG {
            input_dir: dir.path().to_path_buf(),
            output_dir: dir.path().to_path_buf(),
        };
        ssg.generate_index(&posts).unwrap();
        let html = fs::read_to_string(ssg.output_dir.join("index.html")).unwrap();
        let new_pos = html.find("New").unwrap();
        let middle_pos = html.find("Middle").unwrap();
        let old_pos = html.find("Old").unwrap();
        assert!(new_pos < middle_pos);
        assert!(middle_pos < old_pos);
    }

    #[test]
    fn test_css_has_media_queries() {
        assert!(CSS_ASSET.contains("@media"));
    }

    #[test]
    fn test_css_has_dark_mode() {
        assert!(CSS_ASSET.contains("prefers-color-scheme: dark"));
        assert!(CSS_ASSET.contains("[data-theme"));
    }

    #[test]
    fn test_js_has_theme_toggle() {
        assert!(JS_ASSET.contains("theme-toggle"));
        assert!(JS_ASSET.contains("post-search"));
    }

    #[test]
    fn test_html_template_has_nav() {
        assert!(HTML_TEMPLATE.contains("<nav"));
        assert!(HTML_TEMPLATE.contains("theme-toggle"));
    }

    #[test]
    fn test_index_has_search_input() {
        let dir = tempdir().unwrap();
        let ssg = DevLogSSG {
            input_dir: dir.path().to_path_buf(),
            output_dir: dir.path().to_path_buf(),
        };
        let posts = vec![PostMetadata {
            title: "Post 1".into(),
            date: "2026-05-01".into(),
            slug: "post-1.html".into(),
            tags: vec![],
            description: "First".into(),
        }];
        ssg.generate_index(&posts).unwrap();
        let index = fs::read_to_string(ssg.output_dir.join("index.html")).unwrap();
        assert!(index.contains("post-search"));
    }

    #[test]
    fn test_extract_title_with_special_chars() {
        let meta = DevLogSSG::extract_metadata("# Rust & C++: A Comparison", "2026-05-01-rust-cpp");
        assert!(meta.title.contains("&"));
    }
}
